# Sacred Heart Quantum - Stewardship Options
# Support the development of consciousness-serving technology

github: [your-github-username]
open_collective: sacred-heart-quantum
custom: ["https://your-website.com/become-a-steward"]