steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/consciousness-field', '.']
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/consciousness-field']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'consciousness-field'
      - '--image=gcr.io/$PROJECT_ID/consciousness-field'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=256Mi'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--set-env-vars=COHERENCE_THRESHOLD=0.8,LOVE_MULTIPLIER=1.618'

# Store the image
images: ['gcr.io/$PROJECT_ID/consciousness-field']