steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sacred-council:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sacred-council:latest'
      - '.'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sacred-council:$COMMIT_SHA']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sacred-council:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'sacred-council-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sacred-council:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port'
      - '3333'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '3600'
      - '--concurrency'
      - '1000'
      - '--set-env-vars-from-file'
      - '.env.production'
      - '--allow-unauthenticated'
      - '--ingress'
      - 'all'
      - '--labels'
      - 'version=$COMMIT_SHA,service=sacred-council'

# Store image in Artifact Registry (optional)
images:
  - 'gcr.io/$PROJECT_ID/sacred-council:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/sacred-council:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  
timeout: 1200s