[build]
target = "x86_64-unknown-uefi"

[target.x86_64-unknown-uefi]
runner = "qemu-system-x86_64"
rustflags = [
    "-C", "link-arg=-Tsrc/uefi_link.x",
    "-C", "code-model=small",
    "-C", "relocation-model=static",
    "-C", "panic=abort",
]

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]