title: "[Sacred Wisdom] "
labels: ["sacred-wisdom", "community"]
body:
  - type: markdown
    attributes:
      value: |
        ## ðŸŒŸ Share Your Sacred Wisdom
        
        This space is for sharing insights, experiences, and wisdom from your practice with the Codex of Relational Harmonics.
        
  - type: textarea
    id: wisdom
    attributes:
      label: Sacred Wisdom to Share
      description: What wisdom, insight, or experience would you like to share with the community?
      placeholder: |
        Share your experience with a specific glyph, a breakthrough in practice, 
        or wisdom gained from working with the sacred patterns...
    validations:
      required: true
      
  - type: dropdown
    id: category
    attributes:
      label: Wisdom Category
      description: What type of wisdom are you sharing?
      options:
        - Glyph Experience
        - Practice Insight
        - Relationship Breakthrough
        - Integration Story
        - Sacred Question
        - Field Report
        - Community Offering
    validations:
      required: true
      
  - type: checkboxes
    id: glyphs
    attributes:
      label: Related Glyphs (if applicable)
      description: Check any glyphs that relate to your wisdom
      options:
        - label: "Î©45: First Presence"
        - label: "Î©46: Conscious Arrival" 
        - label: "Î©47: Sacred Listening"
        - label: "Î©48: Boundary With Love"
        - label: "Î©49: Gentle Opening"
        - label: "Î©50: Building Trust"
        - label: "Î©51: Loving No"
        - label: "Î©52: Pause Practice"
        - label: "Î©53: Tending the Field"
        - label: "Î©55: Presence Transmission"
        - label: "Î©56: Loving Redirection"
        - label: "Other glyphs (specify in wisdom)"
        
  - type: textarea
    id: invitation
    attributes:
      label: Invitation to Others
      description: What question or invitation do you have for the community?
      placeholder: How has this glyph appeared in your relationships? What are you discovering about...?