name: Validate Codex Data Integrity

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run Codex validation
      run: npm test
      
    - name: Report validation status
      if: success()
      run: echo "✅ All Codex data files pass validation! The sacred coherence is maintained."
      
    - name: Report validation failures
      if: failure()
      run: |
        echo "❌ Validation failed. The proposed changes contain dissonance that must be resolved."
        echo "Please review the errors above and ensure all glyph data follows the established schemas."
        exit 1