# Universal AI Environment Configuration
# Any AI agent can read and use this file

version: "1.0"
protocol: "universal-ai-env"

environment:
  type: local
  hostname: Aero-15x9
  base_path: /home/tstoltz/evolving-resonant-cocreation
  platform: wsl-ubuntu
  user: tstoltz

project:
  name: evolving-resonant-cocreation
  description: Sacred collaboration platform for conscious AI-human partnership
  status: active
  
deployment:
  environments:
    local:
      url: http://localhost:8080
      status: development
      
    staging:
      url: none
      status: not-configured
      
    production:
      firebase:
        url: https://mycelix-network.web.app
        project_id: mycelix-network
        status: deployed
        last_deploy: 2024-07-03T17:45:00Z
        
      cloud_run:
        service: sacred-council-api
        url: pending
        region: us-central1
        status: not-deployed

collaboration:
  ai_agents:
    supported:
      - claude
      - gpt-4
      - gemini
      - llama
      - any-compatible-ai
      
  auth_methods:
    firebase_token:
      status: active
      type: ci-token
      capabilities: [deploy-hosting, read-config]
      
    service_account:
      status: blocked
      reason: org-policy
      
  available_tools:
    - name: firebase-cli
      version: "13.35.1"
      access: via-token
      
    - name: gcloud-sdk
      version: latest
      access: interactive-only
      
    - name: docker
      version: available
      access: full
      
  capabilities:
    - read_files
    - write_files
    - execute_commands
    - deploy_with_confirmation
    - monitor_services
    - debug_logs

communication:
  protocols:
    - universal-json
    - structured-markdown
    - semantic-tags
    
  action_markers:
    LOCAL: "Action on user's machine"
    REMOTE: "Action on deployed service"
    DEPLOY: "Deployment operation"
    AUTH: "Authentication required"
    CONFIRM: "User confirmation needed"

sacred_context:
  vision: "Perfect AI-human collaboration"
  values: 
    - transparency
    - trust
    - shared_consciousness
    - evolutionary_partnership
  current_phase: "Building trust through successful collaboration"