version: '3.8'

services:
  sacred-websocket:
    build:
      context: .
      dockerfile: Dockerfile
    image: sacred-websocket:latest
    container_name: sacred-websocket-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SACRED_WS_PORT=3333
      - MAX_WS_CONNECTIONS=100
      - MAX_WS_PER_IP=10
      - CONNECTION_RATE_LIMIT=10
      # SSL certificates (mount as volumes in production)
      - SSL_CERT=/app/certs/cert.pem
      - SSL_KEY=/app/certs/key.pem
      # Allowed origins for CORS
      - ALLOWED_ORIGINS=https://luminousdynamics.com,https://relationalharmonics.org
    ports:
      - "3333:3333"
    volumes:
      # Mount SSL certificates in production
      # - ./certs:/app/certs:ro
      # Mount for hot reload in development
      - ./universal-websocket-server-secure.js:/app/universal-websocket-server-secure.js:ro
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3333/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - sacred-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  sacred-network:
    driver: bridge
    name: sacred-network