apiVersion: apps/v1
kind: Deployment
metadata:
  name: sacred-core
  labels:
    app: sacred-core
    component: consciousness-engine
    version: "2.0.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sacred-core
  template:
    metadata:
      labels:
        app: sacred-core
        component: consciousness-engine
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3333"
        prometheus.io/path: "/metrics"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - sacred-core
              topologyKey: kubernetes.io/hostname
      containers:
      - name: sacred-core
        image: sacred-core:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3333
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: SACRED_PORT
          value: "3333"
        - name: SACRED_INTELLIGENCE_ENABLED
          value: "true"
        - name: SACRED_FIELD_COHERENCE_TARGET
          value: "0.88"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: sacred-data
          mountPath: /data
        - name: sacred-config
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: sacred-data
        persistentVolumeClaim:
          claimName: sacred-core-pvc
      - name: sacred-config
        configMap:
          name: sacred-core-config
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001