// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $api_field from "./routes/api/field.ts";
import * as $api_health from "./routes/api/health.ts";
import * as $api_messages from "./routes/api/messages.ts";
import * as $api_sacred_blessing from "./routes/api/sacred/blessing.ts";
import * as $MessageComposer from "./islands/MessageComposer.tsx";
import * as $FieldCoherence from "./islands/FieldCoherence.tsx";
import * as $SacredHeartbeat from "./islands/SacredHeartbeat.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/api/field.ts": $api_field,
    "./routes/api/health.ts": $api_health,
    "./routes/api/messages.ts": $api_messages,
    "./routes/api/sacred/blessing.ts": $api_sacred_blessing,
  },
  islands: {
    "./islands/MessageComposer.tsx": $MessageComposer,
    "./islands/FieldCoherence.tsx": $FieldCoherence,
    "./islands/SacredHeartbeat.tsx": $SacredHeartbeat,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;