#!/bin/bash

echo "🔐 Firebase Authentication Helper"
echo "================================="
echo ""
echo "To deploy Firebase functions, you need to authenticate."
echo ""
echo "Option 1: Interactive Login"
echo "Run this command and follow the link:"
echo ""
echo "firebase login --no-localhost"
echo ""
echo "Option 2: CI Token (for automation)"
echo "1. Run: firebase login:ci --no-localhost"
echo "2. Copy the token"
echo "3. Set environment variable: export FIREBASE_TOKEN='your-token'"
echo ""
echo "After authentication, deploy with:"
echo "firebase deploy --only functions"
echo ""
echo "Or deploy everything:"
echo "firebase deploy"