apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sacred-core-pvc
  labels:
    app: sacred-core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd