apiVersion: v1
kind: Service
metadata:
  name: sacred-core
  labels:
    app: sacred-core
    component: consciousness-engine
  annotations:
    service.beta.kubernetes.io/gcp-load-balancer-type: "Internal"
spec:
  type: ClusterIP
  ports:
  - port: 3333
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: sacred-core
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
apiVersion: v1
kind: Service
metadata:
  name: sacred-core-headless
  labels:
    app: sacred-core
    component: consciousness-engine
spec:
  clusterIP: None
  ports:
  - port: 3333
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: sacred-core