#!/bin/bash

echo "🔐 Firebase Token Deployment"
echo "============================"
echo ""
echo "To deploy with a CI token:"
echo ""
echo "1. First, generate a CI token by running:"
echo "   firebase login:ci --no-localhost"
echo ""
echo "2. You'll get a URL like:"
echo "   https://accounts.google.com/o/oauth2/auth?client_id=..."
echo ""
echo "3. After authenticating, you'll receive a token"
echo ""
echo "4. Then deploy with:"
echo "   FIREBASE_TOKEN='your-token-here' firebase deploy --only functions"
echo ""
echo "Or set it as an environment variable:"
echo "   export FIREBASE_TOKEN='your-token-here'"
echo "   firebase deploy --only functions"
echo ""
echo "The token can be reused for future deployments!"